DATASET:
  BATCH_SIZE: 1
  IMG_SIZE: 1024
  MEAN:
  - 0.485
  - 0.456
  - 0.406
  NUM_CLASSES: 1
  NUM_WORKERS: 4
  DATA_ROOT: /home/haipeng/Code/Data/BIGSHA
  STD:
  - 0.229
  - 0.224
  - 0.225
MODEL:
  CKP_PATH: ''
  END_WARM_STEP: 1
  RESUME_PATH: ''
  START_WARM_STEP: 0
OUTPUT:
  CKPT: /ckpt_path
  EXP_NAME: Deeplabv3
  HOME: ./output/
  LOG: /log_path
  MODEL_NAME: deeplabv3
  RESULT: /pred_result
  STORE_EPOCH: 2
  TB: /tb_path
SEED: 42
SOLVER:
  EPOCH: 100
  OPTIM:
    NAME: AdamW
    LR: 0.00005
    DECAY: 0.001
    MOMENTUM: 0.9
  LINEAR_SCHEDULE: # Linear
    IS_USE: 1
    MILESTONGS: [9999999]
    GAMMA: 0.8
  CA_SCHEDULE: # CosineAnnel
    IS_USE: 0
    TMAX: 150
  CLR_SCEDULE: # CosineLR
    IS_USE: 0
    WARM_LR: 0.01
    CYCLE_DECAY: 0.5
    WARM_EPOCH: 10


